version: "3.9"

services:
  db:
    image: postgres:16
    container_name: movies_db
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootroot
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    networks:
      - movies_net

  web:
    build: .
    container_name: movies_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - movies_net

networks:
  movies_net:

volumes:
  pgdata:
